logging:
  level:
    .: ERROR
    org.springframework: INFO
    com.amertkara: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO

spring:
  profiles:
    active: "dev-mysql"
---
spring:
  profiles: dev-mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/campsitemanager?useSSL=false"
    username: "root"
    password: ""
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      ddl-auto: none
---
spring:
  profiles: dev-h2
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL"
    username: "sa"
    password: "sa"
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: none
---
spring:
  profiles: docker-mysql
  datasource:
    url: "jdbc:mysql://mysql:3306/campsitemanager?useSSL=false"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      ddl-auto: none
---