logging:
  level:
    .: ERROR
    org.springframework: INFO
    com.amertkara: DEBUG

spring:
  profiles:
    active: "dev-mysql"
---
spring:
  profiles: dev-mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/campsitemanager?useSSL=false"
    username: "root"
    password: ""
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      ddl-auto: validate
---