package com.amertkara.campsitemanager.exception;

public enum ErrorCode {
	RESERVATION_NOT_FOUND,
	PAYLOAD_NOT_VALID,
	INVALID_DATE_FORMAT,
	INVALID_ARRIVAL_DATE,
	INVALID_RESERVATION_DURATION,
	OVERLAPPING_DATES
}
